import { z } from "zod";
import { NodeDefinition } from "../types/node.types";

export const openrouterLlmInputSchema = z.object({
  prompt: z.string({ required_error: "Prompt is required" }).min(1, "Prompt is required"),
  systemPrompt: z.string().nullable().optional(),
  image_urls: z.array(z.string()).optional(),
  video_urls: z.array(z.string()).optional(),
  audio_urls: z.array(z.string()).optional(),
  temperature: z.number().min(0).max(2).optional(),
  maxTokens: z.number().min(1).max(8192).optional(),
  reasoning: z.boolean().optional(),
  topP: z.number().min(0).max(1).optional(),
  topK: z.number().min(0).max(500).optional(),
  frequencyPenalty: z.number().min(-2).max(2).optional(),
  presencePenalty: z.number().min(-2).max(2).optional(),
  repetitionPenalty: z.number().min(0).max(2).optional(),
  minP: z.number().min(0).max(1).optional(),
  topA: z.number().min(0).max(1).optional(),
  seed: z.number().min(0).optional(),
  stop: z.string().nullable().optional(),
  response_format: z.boolean().optional(),
});

export const openrouterLlmOutputSchema = z.object({
  response: z.string(),
});

export const openrouterLlmDefinition: NodeDefinition = {
  type: "openRouter",
  name: "OpenRouter",
  description: "Generate text using OpenRouter (multi-model API)",
  category: "text",
  icon: "Sparkles",
  color: "blue",
  credits: {
    base: 450000, // static hold/charge until usage.cost billing; UI uses dynamic estimate
  },
  inputs: [
    {
      key: "prompt",
      label: "Prompt",
      type: "textarea",
      required: true,
      group: "primary",
      placeholder: "Enter your prompt...",
      tooltip: "Main user message sent to the model",
      handle: { type: "text", color: "#f59e0b" },
    },
    {
      key: "systemPrompt",
      label: "System Prompt",
      type: "textarea",
      group: "primary",
      defaultValue: "",
      placeholder: "You are a helpful assistant...",
      tooltip: "Optional system instructions for the model",
      handle: { type: "text", color: "#f59e0b" },
    },
    {
      key: "image_urls",
      label: "Image (Vision)",
      type: "image-array",
      group: "primary",
      tooltip: "Upload up to 10 images for vision models",
      handle: { type: "image", color: "#3b82f6" },
    },
    {
      key: "video_urls",
      label: "Video",
      type: "video-array",
      group: "primary",
      tooltip: "Upload up to 7 videos",
      handle: { type: "video", color: "#22c55e" },
    },
    {
      key: "audio_urls",
      label: "Audio",
      type: "audio-array",
      group: "primary",
      tooltip: "Upload up to 5 audio files",
      handle: { type: "audio", color: "#06b6d4" },
    },
    {
      key: "temperature",
      label: "Temperature",
      type: "slider",
      group: "settings",
      defaultValue: 0.5,
      min: 0,
      max: 2,
      step: 0.1,
      tooltip: "Controls randomness. Lower = more focused, higher = more creative.",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "maxTokens",
      label: "Max Tokens",
      type: "number",
      group: "settings",
      defaultValue: 1024,
      min: 1,
      max: 8192,
      step: 1,
      tooltip: "Maximum tokens in the model response",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "reasoning",
      label: "Reasoning",
      type: "boolean",
      group: "settings",
      defaultValue: false,
      tooltip: "Enable extended reasoning where the model supports it",
      handle: { type: "text", color: "#6366f1" },
    },
    {
      key: "topP",
      label: "Top P",
      type: "slider",
      group: "settings",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.05,
      tooltip: "Nucleus sampling — consider tokens with top P cumulative probability",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "topK",
      label: "Top K",
      type: "slider",
      group: "settings",
      defaultValue: 0,
      min: 0,
      max: 500,
      step: 1,
      tooltip: "Limit sampling to the top K tokens",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "frequencyPenalty",
      label: "Frequency Penalty",
      type: "slider",
      group: "settings",
      defaultValue: 0,
      min: -2,
      max: 2,
      step: 0.1,
      tooltip: "Penalize tokens based on how often they appear in the text so far",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "presencePenalty",
      label: "Presence Penalty",
      type: "slider",
      group: "settings",
      defaultValue: 0,
      min: -2,
      max: 2,
      step: 0.1,
      tooltip: "Penalize tokens that have already appeared at least once",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "repetitionPenalty",
      label: "Repetition Penalty",
      type: "slider",
      group: "settings",
      defaultValue: 1,
      min: 0,
      max: 2,
      step: 0.05,
      tooltip: "Reduce repetition of the same token sequences",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "minP",
      label: "Min P",
      type: "slider",
      group: "settings",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.05,
      tooltip: "Minimum probability threshold for token sampling",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "topA",
      label: "Top A",
      type: "slider",
      group: "settings",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.05,
      tooltip: "Consider tokens with probability at least top A × max probability",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "seed",
      label: "Seed",
      type: "number",
      group: "settings",
      defaultValue: 0,
      min: 0,
      step: 1,
      tooltip: "Optional seed for reproducible outputs when supported",
      handle: { type: "text", color: "#ec4899" },
    },
    {
      key: "stop",
      label: "Stop Sequences",
      type: "textarea",
      group: "settings",
      defaultValue: "",
      placeholder: "e.g. END, STOP, ###",
      tooltip: "Comma-separated sequences that stop generation",
      handle: { type: "text", color: "#f59e0b" },
    },
    {
      key: "response_format",
      label: "JSON Mode",
      type: "boolean",
      group: "settings",
      defaultValue: false,
      tooltip: "Request JSON-formatted output when the model supports it",
      handle: { type: "text", color: "#6366f1" },
    },
  ],
  outputs: [
    {
      key: "response",
      label: "Response",
      type: "text",
      handle: { type: "text", color: "#f59e0b" },
    },
  ],
  limits: {
    prompt: { maxLength: 32000 },
    systemPrompt: { maxLength: 32000 },
    image_urls: {
      mediaKind: "image",
      maxCount: 10,
      maxSizeMb: 15,
      maxWidth: 4096,
      maxHeight: 4096,
    },
    video_urls: {
      mediaKind: "video",
      maxCount: 7,
      maxSizeMb: 100,
      maxDurationSeconds: 600,
    },
    audio_urls: {
      mediaKind: "audio",
      maxCount: 5,
      maxSizeMb: 50,
      maxDurationSeconds: 600,
    },
  },
  inputSchema: openrouterLlmInputSchema,
  outputSchema: openrouterLlmOutputSchema,
  defaultTimeoutSeconds: 15,
  retryPerProvider: 1,
  providers: [
    {
      id: "main-openrouter",
      kind: "openrouter",
      timeoutSeconds: 15,
      model: "google/gemini-2.5-flash",
    },
    {
      id: "backup-stub",
      kind: "stub",
      stubDelaySeconds: 2,
      stubTextTemplate:
        '[Backup Provider Stub Response]\nThis is a fallback response because the primary OpenRouter free model failed or timed out.\n\nPrompt: "{{prompt}}"',
    },
  ],
};
